Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2018-11, with the labels that each got.

#467 Add tags support for Neutron Routers
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_router_v2.go
  openstack/resource_openstack_networking_tags_v2_test.go
  website/docs/r/networking_floatingip_v2.html.markdown
  website/docs/r/networking_router_v2.html.markdown
Labels: size/M

#466 Add tags support for Neutron floatingips
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_tags_v2_test.go
  website/docs/r/networking_floatingip_v2.html.markdown
Labels: size/S

#469 Networking v2: Enable trunk tests
  openstack/resource_openstack_networking_trunk_v2_test.go
Labels: size/XS

#477 Internal: compute v2 floatingip cleanup
  openstack/resource_openstack_compute_floatingip_v2.go
Labels: size/XS

#470 Compute v2: openstack_compute_interface_attach
  openstack/provider.go
  openstack/resource_openstack_compute_interface_attach_v2.go
  openstack/resource_openstack_compute_interface_attach_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/testing/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/testing/fixtures.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/attachinterfaces/urls.go
  vendor/github.com/gophercloud/gophercloud/testhelper/client/fake.go
  vendor/github.com/gophercloud/gophercloud/testhelper/convenience.go
  vendor/github.com/gophercloud/gophercloud/testhelper/doc.go
  vendor/github.com/gophercloud/gophercloud/testhelper/http_responses.go
  vendor/vendor.json
  website/docs/r/compute_interface_attach_v2.html.markdown
  website/openstack.erb
Labels: size/XXL

#472 Internal: compute v2 flavor cleanup
  openstack/compute_flavor_v2.go
  openstack/compute_flavor_v2_test.go
  openstack/data_source_openstack_compute_flavor_v2.go
  openstack/data_source_openstack_compute_flavor_v2_test.go
  openstack/import_openstack_compute_flavor_v2_test.go
  openstack/resource_openstack_compute_flavor_v2.go
  openstack/resource_openstack_compute_flavor_v2_test.go
Labels: size/M

#476 Internal: compute v2 keypair cleanup
  openstack/compute_keypair_v2.go
  openstack/compute_keypair_v2_test.go
  openstack/data_source_openstack_compute_keypair_v2.go
  openstack/resource_openstack_compute_keypair_v2.go
  openstack/types.go
Labels: size/M

#478 Internal: compute v2 secgroup cleanup
  openstack/compute_secgroup_v2.go
  openstack/compute_secgroup_v2_test.go
  openstack/resource_openstack_compute_secgroup_v2.go
  openstack/resource_openstack_compute_secgroup_v2_test.go
Labels: size/XL

#482 Internal: small fixes from previous cleanup
  openstack/resource_openstack_compute_flavor_v2.go
  openstack/resource_openstack_compute_keypair_v2.go
Labels: size/XS

#258 Networking V2: add DHCP opts to the port resource
  openstack/import_openstack_networking_port_v2_test.go
  openstack/networking_port_v2.go
  openstack/networking_port_v2_test.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/extradhcpopts/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/extradhcpopts/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/extradhcpopts/results.go
  vendor/vendor.json
  website/docs/r/networking_port_v2.html.markdown
Labels: size/XL

#486 Network v2: Rename extra_dhcp_opts to extra_dhcp_option
  openstack/networking_port_v2.go
  openstack/networking_port_v2_test.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  website/docs/r/networking_port_v2.html.markdown
Labels: size/L

#481 Compute v2: Adding fingerprint to keypair data source
  openstack/data_source_openstack_compute_keypair_v2.go
  openstack/data_source_openstack_compute_keypair_v2_test.go
  website/docs/d/compute_keypair_v2.html.markdown
Labels: size/XS

#480 Compute v2: Adding extra_specs to flavor data source
  openstack/data_source_openstack_compute_flavor_v2.go
  openstack/data_source_openstack_compute_flavor_v2_test.go
  website/docs/d/compute_flavor_v2.html.markdown
Labels: size/M

#485 Make the tenantnetworks API not required
  openstack/compute_instance_v2_networking.go
Labels: size/S

#483 Internal: compute v2 servergroup cleanup
  openstack/compute_servergroup_v2.go
  openstack/compute_servergroup_v2_test.go
  openstack/resource_openstack_compute_servergroup_v2.go
  openstack/resource_openstack_compute_servergroup_v2_test.go
  openstack/types.go
Labels: size/L

#489 Vendor: Updating Gophercloud
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/vendor.json
Labels: size/XL

#465 Enable object versioning
  openstack/resource_openstack_objectstorage_container_v1.go
  website/docs/r/objectstorage_container_v1.html.markdown
Labels: size/M

#488 ContainerInfraV1: add Cluster datasource
  openstack/data_source_openstack_containerinfra_cluster_v1.go
  openstack/data_source_openstack_containerinfra_cluster_v1_test.go
  openstack/provider.go
  openstack/resource_openstack_containerinfra_cluster_v1_test.go
  website/docs/d/containerinfra_cluster_v1.html.markdown
  website/openstack.erb
Labels: size/XL

#490 ComputeV2: add soft policies
  openstack/compute_servergroup_v2.go
  openstack/compute_servergroup_v2_test.go
  openstack/resource_openstack_compute_servergroup_v2.go
  openstack/resource_openstack_compute_servergroup_v2_test.go
  website/docs/r/compute_servergroup_v2.html.markdown
Labels: size/M

#496 Allow a VM to be in a state of 'migrating'
  openstack/resource_openstack_compute_instance_v2.go
Labels: size/XS
