Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2018-09, with the labels that each got.

#396 Updating Developer Documentation
  README.md
  website/docs/index.html.markdown
Labels: documentation, size/L

#409 Image Service v2: Support Updating Properties
  openstack/resource_openstack_images_image_v2.go
  openstack/resource_openstack_images_image_v2_test.go
  vendor/github.com/gophercloud/gophercloud/README.md
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/requests.go
  vendor/vendor.json
  website/docs/r/images_image_v2.html.markdown
Labels: size/XL

#412 Object Storage v1: Add regenerate to temp url resource
  openstack/resource_openstack_objectstorage_tempurl_v1.go
  website/docs/r/objectstorage_tempurl_v1.html.markdown
Labels: size/M

#403 ContainerInfraV1: add Cluster template resource
  openstack/config.go
  openstack/import_openstack_containerinfra_clustertemplate_v1_test.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/resource_openstack_containerinfra_clustertemplate_v1.go
  openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/urls.go
  vendor/github.com/hashicorp/terraform/helper/structure/expand_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/flatten_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/normalize_json.go
  vendor/github.com/hashicorp/terraform/helper/structure/suppress_json_diff.go
  vendor/github.com/hashicorp/terraform/helper/validation/validation.go
  vendor/vendor.json
  website/docs/r/containerinfra_clustertemplate_v1.html.markdown
  website/openstack.erb
Labels: size/XXL

#417 Replace deprecated external_gateway
  website/docs/r/networking_router_interface_v2.html.markdown
Labels: size/XS

#415 ContainerInfraV1: add Cluster template datasource
  openstack/data_source_openstack_containerinfra_clustertemplate_v1.go
  openstack/data_source_openstack_containerinfra_clustertemplate_v1_test.go
  openstack/provider.go
  website/docs/d/containerinfra_clustertemplate_v1.html.markdown
  website/openstack.erb
Labels: size/L

#416 Add description field to openstack_networking_secgroup_rule_v2
  openstack/resource_openstack_networking_secgroup_rule_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/secgroups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/db/v1/configurations/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/vendor.json
  website/docs/r/networking_secgroup_rule_v2.html.markdown
Labels: size/L

#422 ComputeV2: add instance vendor_options
  openstack/resource_openstack_compute_instance_v2.go
  openstack/resource_openstack_networking_router_v2.go
  openstack/util.go
  website/docs/r/compute_instance_v2.html.markdown
Labels: size/L

#421 ContainerInfra V1: add Cluster resource
  openstack/import_openstack_containerinfra_cluster_v1_test.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/resource_openstack_containerinfra_cluster_v1.go
  openstack/resource_openstack_containerinfra_cluster_v1_test.go
  openstack/resource_openstack_containerinfra_clustertemplate_v1.go
  openstack/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/urls.go
  vendor/vendor.json
  website/docs/r/containerinfra_cluster_v1.html.markdown
  website/openstack.erb
Labels: size/XXL

#428 Compute v2: Allow power_state of error
  openstack/resource_openstack_compute_instance_v2.go
Labels: size/S

#425 Support acceptance test against OpenStack Rocky release in OpenLab
  .zuul.yaml
Labels: size/XS

#426 Handle rackspace server addresses without type
  openstack/compute_instance_v2_networking.go
Labels: size/XS

#433 Networking v2: Add no_fixed_ip to openstack_networking_port_v2
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  website/docs/r/networking_port_v2.html.markdown
Labels: size/L
