Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2018-12, with the labels that each got.

#448 Block Storage Snapshot Data Sources
  openstack/data_source_openstack_blockstorage_snapshot_v2.go
  openstack/data_source_openstack_blockstorage_snapshot_v2_test.go
  openstack/data_source_openstack_blockstorage_snapshot_v3.go
  openstack/data_source_openstack_blockstorage_snapshot_v3_test.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/types.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/snapshots/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/snapshots/util.go
  vendor/vendor.json
  website/docs/d/blockstorage_snapshot_v2.html.markdown
  website/docs/d/blockstorage_snapshot_v3.html.markdown
  website/openstack.erb
Labels: size/XXL

#505 Internal: port allowed address pairs cleanup
  openstack/networking_port_v2.go
  openstack/networking_port_v2_test.go
  openstack/resource_openstack_networking_port_v2.go
Labels: size/L

#509 Reflect new gophercloud structures
  openstack/resource_openstack_blockstorage_volume_v1.go
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
  openstack/resource_openstack_compute_secgroup_v2.go
  openstack/resource_openstack_dns_recordset_v2.go
  openstack/resource_openstack_dns_zone_v2.go
  openstack/resource_openstack_fw_firewall_v1.go
  openstack/resource_openstack_fw_policy_v1.go
  openstack/resource_openstack_identity_project_v3.go
  openstack/resource_openstack_identity_user_v3.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_pool_v1.go
  openstack/resource_openstack_lb_pool_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_secgroup_v2.go
  openstack/resource_openstack_networking_trunk_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v2/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/secgroups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/db/v1/configurations/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/zones/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/users/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/fwaas/firewalls/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/fwaas/policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/vendor.json
Labels: dependencies, size/XL

#516 LBaaS: Allow LB listener default pool update without the listener re-creation
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_listener_v2_test.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  website/docs/r/lb_listener_v2.html.markdown
Labels: dependencies, documentation, size/S

#515 Manila: Shared file system securityservice and sharenetwork resources
  openstack/config.go
  openstack/import_openstack_sharedfilesystem_securityservice_v2_test.go
  openstack/import_openstack_sharedfilesystem_sharenetwork_v2_test.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/resource_openstack_sharedfilesystem_securityservice_v2.go
  openstack/resource_openstack_sharedfilesystem_securityservice_v2_test.go
  openstack/resource_openstack_sharedfilesystem_sharenetwork_v2.go
  openstack/resource_openstack_sharedfilesystem_sharenetwork_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/securityservices/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/securityservices/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/securityservices/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharenetworks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharenetworks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/sharenetworks/urls.go
  vendor/vendor.json
  website/docs/index.html.markdown
  website/docs/r/sharedfilesystem_securityservice_v2.html.markdown
  website/docs/r/sharedfilesystem_sharenetwork_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#529 Networking V2: add description to the router resource
  openstack/resource_openstack_networking_router_v2.go
  openstack/resource_openstack_networking_router_v2_test.go
  website/docs/r/networking_router_v2.html.markdown
Labels: documentation, size/XS

#535 Networking V2: add description to the secgroup data source
  openstack/data_source_openstack_networking_secgroup_v2.go
  openstack/data_source_openstack_networking_secgroup_v2_test.go
  website/docs/d/networking_secgroup_v2.html.markdown
Labels: documentation, size/XS

#532 Networking V2: add description to the network resource
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_network_v2_test.go
  website/docs/r/networking_network_v2.html.markdown
Labels: documentation, size/XS

#528 Networking V2: add description to the subnet data source
  openstack/data_source_openstack_networking_subnet_v2.go
  openstack/data_source_openstack_networking_subnet_v2_test.go
  website/docs/d/networking_subnet_v2.html.markdown
Labels: documentation, size/XS

#530 Networking V2: add description to the router data source
  openstack/data_source_openstack_networking_router_v2.go
  openstack/data_source_openstack_networking_router_v2_test.go
  website/docs/d/networking_router_v2.html.markdown
Labels: documentation, size/XS

#536 Networking V2: add description to the network data source
  openstack/data_source_openstack_networking_network_v2.go
  openstack/data_source_openstack_networking_network_v2_test.go
  website/docs/d/networking_network_v2.html.markdown
Labels: documentation, size/XS

#523 Networking V2: Add description fields to the floatingip resource
  openstack/data_source_openstack_networking_floatingip_v2.go
  openstack/data_source_openstack_networking_floatingip_v2_test.go
  website/docs/d/networking_floatingip_v2.html.markdown
Labels: documentation, size/XS

#537 LBaaSv2: bump vendor for empty "default_pool_id" update logic
  openstack/resource_openstack_lb_listener_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/results.go
  vendor/vendor.json
Labels: dependencies, size/XXL

#494 fix 493 - explicitly set default bool attributes
  openstack/provider.go
Labels: size/XS

#547 LBaaSv2: Improve LB objects' checks
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_pool_v2.go
Labels: size/L

#543 Internal: block storage volume attach cleanup
  openstack/blockstorage_volume_attach_v2.go
  openstack/blockstorage_volume_attach_v2_test.go
  openstack/blockstorage_volume_attach_v3.go
  openstack/blockstorage_volume_attach_v3_test.go
  openstack/resource_openstack_blockstorage_volume_attach_v2.go
  openstack/resource_openstack_blockstorage_volume_attach_v2_test.go
  openstack/resource_openstack_blockstorage_volume_attach_v3.go
  openstack/resource_openstack_blockstorage_volume_attach_v3_test.go
Labels: size/XL

#551 Provider: Fix flavor detection
  openstack/resource_openstack_compute_instance_v2.go
  openstack/resource_openstack_compute_instance_v2_test.go
  openstack/resource_openstack_containerinfra_cluster_v1.go
Labels: size/M

#524 LBaaSv2: Add resource import feature
  openstack/import_openstack_lb_listener_v2_test.go
  openstack/import_openstack_lb_loadbalancer_v2_test.go
  openstack/import_openstack_lb_member_v2_test.go
  openstack/import_openstack_lb_monitor_v2_test.go
  openstack/import_openstack_lb_pool_v2_test.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_pool_v2.go
  website/docs/r/lb_listener_v2.html.markdown
  website/docs/r/lb_loadbalancer_v2.html.markdown
  website/docs/r/lb_member_v2.html.markdown
  website/docs/r/lb_monitor_v2.html.markdown
  website/docs/r/lb_pool_v2.html.markdown
Labels: documentation, size/L

#545 Internal: Container Infra cleanup
  openstack/containerinfra_shared_v1.go
  openstack/containerinfra_shared_v1_test.go
  openstack/data_source_openstack_containerinfra_cluster_v1.go
  openstack/data_source_openstack_containerinfra_clustertemplate_v1.go
  openstack/resource_openstack_containerinfra_cluster_v1.go
  openstack/resource_openstack_containerinfra_clustertemplate_v1.go
  openstack/util.go
Labels: size/XL

#550 LBaaSv2: Detect individual LB object statuses, don't rely on LB status
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_pool_v2.go
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/l7policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/results.go
  vendor/vendor.json
Labels: dependencies, size/XL

#555 Internal: Fix expandContainerInfraV1LabelsString unit test
  openstack/containerinfra_shared_v1_test.go
Labels: size/XS

#527 LbaaS: Add l7policy resource
  openstack/import_openstack_lb_l7policy_v2_test.go
  openstack/lb_v2_shared.go
  openstack/provider.go
  openstack/resource_openstack_lb_l7policy_v2.go
  openstack/resource_openstack_lb_l7policy_v2_test.go
  website/docs/r/lb_l7policy_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#522 LBaaS: Add l7rule resource
  openstack/import_openstack_lb_l7rule_v2_test.go
  openstack/lb_v2_shared.go
  openstack/provider.go
  openstack/resource_openstack_lb_l7rule_v2.go
  openstack/resource_openstack_lb_l7rule_v2_test.go
  website/docs/r/lb_l7rule_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#558 ComputeV2: add "device_type" and "disk_bus" fields
  openstack/resource_openstack_compute_instance_v2.go
  openstack/resource_openstack_compute_instance_v2_test.go
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/M

#513 NetworkingV2: add transparent_vlan network resource attribute
  openstack/provider_test.go
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_network_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/vlantransparent/results.go
  vendor/vendor.json
  website/docs/r/networking_network_v2.html.markdown
Labels: dependencies, documentation, size/XL
