Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2018-10, with the labels that each got.

#431 Update gophercloud, enable multiattach functionality
  openstack/resource_openstack_blockstorage_volume_v3.go
  openstack/resource_openstack_blockstorage_volume_v3_test.go
  vendor/github.com/gophercloud/gophercloud/auth_options.go
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/vendor.json
  website/docs/r/blockstorage_volume_v3.html.markdown
Labels: size/XL

#441 Acc Tests: Updating LBaaS v2 Member test
  openstack/resource_openstack_lb_member_v2_test.go
Labels: size/XS

#443 DNSv2: Format IPv6 Records
  openstack/resource_openstack_dns_recordset_v2.go
  openstack/resource_openstack_dns_recordset_v2_test.go
Labels: size/M

#445 expected_codes argument description typo
  website/docs/r/lb_monitor_v1.html.markdown
Labels: size/XS

#442 Compute v2: Enable Multiattach Volumes
  openstack/resource_openstack_compute_volume_attach_v2.go
  website/docs/r/compute_volume_attach_v2.html.markdown
Labels: size/S

#451 LBaaS v2: Allow member weights of 0
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_member_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/params.go
  vendor/vendor.json
Labels: size/XL

#452 Identity v3: Acceptance test fixes
  openstack/resource_openstack_identity_project_v3_test.go
  openstack/resource_openstack_identity_role_v3_test.go
  openstack/resource_openstack_identity_user_v3_test.go
Labels: size/S

#446 Network resource - Trunk
  openstack/provider.go
  openstack/resource_openstack_networking_trunk_v2.go
  openstack/resource_openstack_networking_trunk_v2_test.go
  openstack/util.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/attributestags/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/results.go
  vendor/vendor.json
  website/docs/r/networking_trunk_v2.html.markdown
  website/openstack.erb
Labels: size/XXL

#447 Allow to specify flavor access for tenants
  openstack/import_openstack_compute_flavor_access_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_compute_flavor_access_v2.go
  openstack/resource_openstack_compute_flavor_access_v2_test.go
  website/docs/r/compute_flavor_access_v2.html.markdown
  website/openstack.erb
Labels: size/XL

#459 Add tags support for Neutron Subnets
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_subnet_v2.go
  openstack/resource_openstack_networking_tags_v2_test.go
  website/docs/r/networking_network_v2.html.markdown
  website/docs/r/networking_subnet_v2.html.markdown
Labels: size/M

#454 Add tags support for Neutron Networks
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_tags_v2_test.go
  website/docs/r/networking_network_v2.html.markdown
Labels: size/M
