Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-09, with the labels that each got.

#845 Identity V3: fix role assignment list
  openstack/identity_role_assignment_v3.go
Labels: size/S

#833 Fixes #716 "Managing projects requires admin role" by using the users…
  openstack/data_source_openstack_identity_project_v3.go
Labels: size/S

#846 Key manager V1: Add containers data source
  openstack/data_source_openstack_keymanager_container_v1.go
  openstack/data_source_openstack_keymanager_container_v1_test.go
  openstack/data_source_openstack_keymanager_secret_v1.go
  openstack/data_source_openstack_keymanager_secret_v1_test.go
  openstack/provider.go
  openstack/resource_openstack_keymanager_container_v1.go
  website/docs/d/keymanager_container_v1.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#851 Identity V3: Fix panic within the domain scope
  openstack/data_source_openstack_identity_auth_scope_v3.go
Labels: size/XS

#856 Compute V2: Fix not found logic for the flavor access
  openstack/resource_openstack_compute_flavor_access_v2.go
Labels: size/XS

#857 Identity V3: Fix not found logic detection for the role assignments
  openstack/identity_role_assignment_v3.go
Labels: size/XS

#855 Compute V2: Read flavor's ephemeral option
  openstack/resource_openstack_compute_flavor_v2.go
Labels: size/XS

#849 Add ability to control caching
  CHANGELOG.md
  openstack/config.go
  openstack/provider.go
  openstack/types.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#865 Refactor formatting headers
  go.mod
  go.sum
  openstack/types.go
  openstack/util.go
  openstack/util_test.go
  vendor/github.com/Unknwon/com/.gitignore
  vendor/github.com/Unknwon/com/.travis.yml
  vendor/github.com/Unknwon/com/LICENSE
  vendor/github.com/Unknwon/com/README.md
  vendor/github.com/Unknwon/com/cmd.go
  vendor/github.com/Unknwon/com/convert.go
  vendor/github.com/Unknwon/com/dir.go
  vendor/github.com/Unknwon/com/file.go
  vendor/github.com/Unknwon/com/html.go
  vendor/github.com/Unknwon/com/http.go
  vendor/github.com/Unknwon/com/math.go
  vendor/github.com/Unknwon/com/path.go
  vendor/github.com/Unknwon/com/regex.go
  vendor/github.com/Unknwon/com/slice.go
  vendor/github.com/Unknwon/com/string.go
  vendor/github.com/Unknwon/com/time.go
  vendor/github.com/Unknwon/com/url.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#871 Identity V3: Show domain scope info
  go.mod
  go.sum
  openstack/data_source_openstack_identity_auth_scope_v3.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/modules.txt
  website/docs/d/identity_auth_scope_v3.html.markdown
Labels: dependencies, documentation, size/M

#861 Identity: authenticate against identity only, when it is needed
  openstack/config.go
  openstack/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/M

#874 Identity V3: Add description support to the user and group data sources
  openstack/data_source_openstack_identity_group_v3.go
  openstack/data_source_openstack_identity_user_v3.go
  website/docs/d/identity_group_v3.html.markdown
  website/docs/d/identity_user_v3.html.markdown
Labels: documentation, size/XS

#872 Glance v2: Add image share resource
  openstack/data_source_openstack_images_image_v2.go
  openstack/images_image_v2.go
  openstack/import_openstack_images_image_access_accept_v2_test.go
  openstack/import_openstack_images_image_access_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_images_image_access_accept_v2.go
  openstack/resource_openstack_images_image_access_accept_v2_test.go
  openstack/resource_openstack_images_image_access_v2.go
  openstack/resource_openstack_images_image_access_v2_test.go
  openstack/resource_openstack_images_image_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/members/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/members/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/members/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/members/urls.go
  vendor/modules.txt
  website/docs/r/images_image_access_accept_v2.html.markdown
  website/docs/r/images_image_access_v2.html.markdown
  website/docs/r/images_image_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#877 LoadBalancer listener V2: fix Read method
  go.mod
  go.sum
  openstack/import_openstack_lb_listener_v2_test.go
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_listener_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/modules.txt
Labels: dependencies, size/L

#878 Check for the client error
  openstack/data_source_openstack_identity_auth_scope_v3.go
  openstack/resource_openstack_compute_floatingip_associate_v2_test.go
Labels: size/XS
