Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-03, with the labels that each got.

#701 Debug: Allow JSON array unmarshalling in debug mode
  openstack/types.go
Labels: size/XS

#700 Acc Tests: Fixing test fixtures
  openstack/data_source_openstack_networking_port_v2_test.go
  openstack/resource_openstack_identity_user_v3_test.go
  openstack/resource_openstack_networking_network_v2_test.go
Labels: size/XS

#681 Networking v2: Network Port Security
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_network_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/results.go
  vendor/modules.txt
  website/docs/r/networking_network_v2.html.markdown
Labels: dependencies, documentation, size/XL

#703 Docs: Fix incorrect floating IP reference
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#682 Networking v2: Port Port Security
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  website/docs/r/networking_port_v2.html.markdown
Labels: dependencies, documentation, size/L

#711 Networking v2: Fix security group acceptance test
  openstack/resource_openstack_networking_secgroup_rule_v2_test.go
Labels: size/XS

#695 Networking V2: Handle multiple dhcp options in port data source
  openstack/data_source_openstack_networking_port_v2.go
Labels: size/XS

#713 Internal: Use ErrDefault409
  go.mod
  go.sum
  openstack/fw_policy_v1.go
  openstack/networking_network_v2.go
  openstack/networking_router_interface_v2.go
  openstack/networking_subnetpool_v2.go
  openstack/resource_openstack_blockstorage_volume_v1.go
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
  openstack/resource_openstack_lb_monitor_v1.go
  openstack/resource_openstack_networking_secgroup_v2.go
  openstack/resource_openstack_networking_subnet_v2.go
  openstack/resource_openstack_objectstorage_container_v1.go
  openstack/resource_openstack_vpnaas_ipsec_policy_v2.go
  openstack/util.go
  vendor/github.com/gophercloud/gophercloud/.travis.yml
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/auth_env.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clustertemplates/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/applicationcredentials/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/github.com/gophercloud/gophercloud/service_client.go
  vendor/modules.txt
Labels: dependencies, size/L

#626 Networking V2: Add trunk data source
  openstack/data_source_openstack_networking_trunk_v2.go
  openstack/data_source_openstack_networking_trunk_v2_test.go
  openstack/provider.go
  website/docs/d/networking_trunk_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#710 add multi-vm with corresponding floating ip example
  examples/multiple-vm-with-floating-ip/Readme.md
  examples/multiple-vm-with-floating-ip/main.tf
  examples/multiple-vm-with-floating-ip/openrc.sample
  examples/multiple-vm-with-floating-ip/variables.tf
Labels: size/M

#693 Networking V2: Introduce port binding support
  go.sum
  openstack/data_source_openstack_networking_port_v2.go
  openstack/networking_port_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/results.go
  vendor/modules.txt
  website/docs/d/networking_port_v2.html.markdown
  website/docs/r/networking_port_v2.html.markdown
Labels: dependencies, documentation, size/XL

#708 Networking V2: Add MTU support for the network resources
  openstack/data_source_openstack_networking_network_v2.go
  openstack/networking_network_v2.go
  openstack/resource_openstack_networking_network_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/mtu/results.go
  vendor/modules.txt
  website/docs/d/networking_network_v2.html.markdown
  website/docs/r/networking_network_v2.html.markdown
Labels: dependencies, documentation, size/L

#706 Networking V2: Add DNS support for the port, floating IP, network
  openstack/data_source_openstack_networking_floatingip_v2.go
  openstack/data_source_openstack_networking_network_v2.go
  openstack/data_source_openstack_networking_port_ids_v2.go
  openstack/data_source_openstack_networking_port_v2.go
  openstack/networking_floatingip_v2.go
  openstack/networking_network_v2.go
  openstack/networking_port_v2.go
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_port_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/dns/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/dns/results.go
  vendor/modules.txt
  website/docs/d/networking_floatingip_v2.html.markdown
  website/docs/d/networking_network_v2.html.markdown
  website/docs/d/networking_port_v2.html.markdown
  website/docs/r/networking_floatingip_v2.html.markdown
  website/docs/r/networking_network_v2.html.markdown
  website/docs/r/networking_port_v2.html.markdown
Labels: dependencies, documentation, size/XL

#709 Networking V2: Allow floatingip associate with the fixed_ip
  openstack/resource_openstack_networking_floatingip_associate_v2.go
  openstack/resource_openstack_networking_floatingip_associate_v2_test.go
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_floatingip_v2_test.go
Labels: size/L
