Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-06, with the labels that each got.

#765 Docs: Fix docs for subnet allocation pool
  website/docs/r/networking_subnet_v2.html.markdown
Labels: documentation, size/XS

#766 Acc Tests: Update lowercase security group test
  openstack/resource_openstack_compute_secgroup_v2_test.go
Labels: size/XS

#772 Acc Tests: Remove flatmap
  openstack/resource_openstack_networking_tags_v2_test.go
  openstack/resource_openstack_vpnaas_endpoint_group_v2_test.go
  openstack/resource_openstack_vpnaas_ike_policy_v2.go
  openstack/resource_openstack_vpnaas_ike_policy_v2_test.go
  openstack/resource_openstack_vpnaas_ipsec_policy_v2_test.go
  openstack/util.go
Labels: size/M

#771 Compute v2: Fix scheduler hints query
  go.mod
  go.sum
  openstack/resource_openstack_compute_instance_v2.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go
  vendor/modules.txt
  website/docs/r/compute_instance_v2.html.markdown
Labels: dependencies, documentation, size/M

#774 Networking V2: add QoS Policy resource
  go.mod
  go.sum
  openstack/import_openstack_networking_qos_policy_v2_test.go
  openstack/networking_qos_policy_v2.go
  openstack/provider.go
  openstack/resource_openstack_networking_qos_policy_v2.go
  openstack/resource_openstack_networking_qos_policy_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/urls.go
  vendor/modules.txt
  website/docs/r/networking_qos_policy_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#777 Readme: update Terraform and Go versions
  .go-version
  .travis.yml
  README.md
Labels: size/XS

#779 Networking V2: add QoS Policy datasource
  openstack/data_source_openstack_networking_qos_policy_v2.go
  openstack/data_source_openstack_networking_qos_policy_v2_test.go
  openstack/provider.go
  website/docs/d/networking_qos_policy_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#778 Website: fix networking_qos_policy_v2 resource doc
  website/docs/r/networking_qos_policy_v2.html.markdown
Labels: documentation, size/XS

#780 Networking V2: add QoS policy field for Network
  openstack/networking_network_v2.go
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_network_v2_test.go
  website/docs/r/networking_network_v2.html.markdown
Labels: documentation, size/M

#782 Networking V2: group QoS policy imports
  openstack/networking_qos_policy_v2.go
  openstack/resource_openstack_networking_qos_policy_v2.go
  openstack/resource_openstack_networking_qos_policy_v2_test.go
Labels: size/XS

#781 Networking V2: add QoS policy field for Port
  openstack/networking_port_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
  website/docs/r/networking_port_v2.html.markdown
Labels: documentation, size/M

#783 Networking V2: add QoS BW limit rule resource
  go.mod
  go.sum
  openstack/import_openstack_networking_qos_bandwidth_limit_rule_v2_test.go
  openstack/networking_qos_rule_v2.go
  openstack/networking_qos_rule_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2.go
  openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/rules/urls.go
  vendor/modules.txt
  website/docs/r/networking_qos_bandwidth_limit_rule_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#784 Networking V2: add QoS DSCP marking rule resource
  openstack/import_openstack_networking_qos_dscp_marking_rule_v2_test.go
  openstack/networking_qos_rule_v2.go
  openstack/provider.go
  openstack/resource_openstack_networking_qos_dscp_marking_rule_v2.go
  openstack/resource_openstack_networking_qos_dscp_marking_rule_v2_test.go
  website/docs/r/networking_qos_dscp_marking_rule_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL
