Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-07, with the labels that each got.

#791 Networking V2: set QoS bw limit default direction
  openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2.go
  openstack/resource_openstack_networking_qos_bandwidth_limit_rule_v2_test.go
  website/docs/r/networking_qos_bandwidth_limit_rule_v2.html.markdown
Labels: documentation, size/XS

#788 Networking V2: add QoS bw limit rule datasource
  openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2.go
  openstack/data_source_openstack_networking_qos_bandwidth_limit_rule_v2_test.go
  openstack/provider.go
  website/docs/d/networking_qos_bandwidth_limit_rule_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#789 Networking V2: add QoS dscp marking datasource
  openstack/data_source_networking_qos_dscp_marking_rule_v2.go
  openstack/data_source_networking_qos_dscp_marking_rule_v2_test.go
  openstack/provider.go
  website/docs/d/networking_qos_dscp_marking_rule_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#790 Networking V2: add QoS min bw rule resource
  openstack/networking_qos_rule_v2.go
  openstack/provider.go
  openstack/resource_openstack_networking_qos_minimum_bandwidth_rule_v2.go
  openstack/resource_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go
  website/docs/r/networking_qos_minimum_bandwidth_rule_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#793 Networking V2: add QoS min bw datasource
  openstack/data_source_openstack_networking_qos_minimum_bandwidth_rule_v2.go
  openstack/data_source_openstack_networking_qos_minimum_bandwidth_rule_v2_test.go
  openstack/provider.go
  website/docs/d/networking_qos_minimum_bandwidth_rule_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#792 Networking V2: rename QoS DSCP marking ds file
  openstack/data_source_openstack_networking_qos_dscp_marking_rule_v2.go
  openstack/data_source_openstack_networking_qos_dscp_marking_rule_v2_test.go
Labels: size/XS

#797 docs: Formalize inline HCL codes to canonical format
  website/docs/d/images_image_v2.html.markdown
  website/docs/r/blockstorage_volume_attach_v2.html.markdown
  website/docs/r/blockstorage_volume_attach_v3.html.markdown
  website/docs/r/compute_flavor_access_v2.html.markdown
  website/docs/r/compute_flavor_v2.html.markdown
  website/docs/r/compute_instance_v2.html.markdown
  website/docs/r/compute_interface_attach_v2.html.markdown
  website/docs/r/compute_secgroup_v2.html.markdown
  website/docs/r/compute_volume_attach_v2.html.markdown
  website/docs/r/containerinfra_cluster_v1.html.markdown
  website/docs/r/dns_recordset_v2.html.markdown
  website/docs/r/dns_zone_v2.html.markdown
  website/docs/r/identity_project_v3.html.markdown
  website/docs/r/identity_role_assignment_v3.html.markdown
  website/docs/r/identity_user_v3.html.markdown
  website/docs/r/images_image_v2.html.markdown
  website/docs/r/lb_l7policy_v2.html.markdown
  website/docs/r/lb_l7rule_v2.html.markdown
  website/docs/r/networking_floatingip_associate_v2.html.markdown
  website/docs/r/networking_port_secgroup_associate_v2.html.markdown
  website/docs/r/networking_qos_dscp_marking_rule_v2.html.markdown
  website/docs/r/networking_qos_minimum_bandwidth_rule_v2.html.markdown
  website/docs/r/networking_secgroup_v2.html.markdown
  website/docs/r/networking_subnetpool_v2.html.markdown
  website/docs/r/networking_trunk_v2.html.markdown
  website/docs/r/objectstorage_container_v1.html.markdown
  website/docs/r/objectstorage_object_v1.html.markdown
  website/docs/r/objectstorage_tempurl_v1.html.markdown
  website/docs/r/sharedfilesystem_share_access_v2.html.markdown
  website/docs/r/sharedfilesystem_share_v2.html.markdown
  website/docs/r/sharedfilesystem_sharenetwork_v2.html.markdown
  website/docs/r/vpnaas_endpoint_group_v2.html.markdown
  website/docs/r/vpnaas_service_v2.html.markdown
  website/docs/r/vpnaas_site_connection_v2.html.markdown
Labels: documentation, size/XL

#799 vpnaas_site_connection: Switch admin_state_up default to true
  openstack/resource_openstack_vpnaas_site_connection.go
Labels: size/XS

#800 openstack_compute_volume_attach_v3 doesn't exist
  website/docs/r/blockstorage_volume_attach_v3.html.markdown
Labels: documentation, size/XS

#768 Enable import instance
  openstack/import_openstack_compute_instance_v2_test.go
  openstack/resource_openstack_compute_instance_v2.go
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XL

#809 Gofmt cleanup after the compute resource import
  openstack/import_openstack_compute_instance_v2_test.go
Labels: size/XS

#726 Check type assertion for the dns_nameservers in subnet
  openstack/resource_openstack_networking_subnet_v2.go
Labels: size/XS

#807 Keymanager V1: secrets resource
  openstack/config.go
  openstack/import_openstack_keymanager_secret_v1_test.go
  openstack/keymanager_secret_v1.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/resource_openstack_keymanager_secret_v1.go
  openstack/resource_openstack_keymanager_secret_v1_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/secrets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/secrets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/secrets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/secrets/urls.go
  vendor/modules.txt
  website/docs/r/keymanager_secret_v1.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL
