Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-12, with the labels that each got.

#928 Data source for openstack_blockstorage_volume_v2
  openstack/data_source_openstack_blockstorage_volume_v2.go
  openstack/data_source_openstack_blockstorage_volume_v2_test.go
  openstack/provider.go
  website/docs/d/blockstorage_volume_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#943 Update clouds.yaml doc reference to openstacksdk
  website/docs/index.html.markdown
Labels: documentation, size/XS

#942 Added support for shelved compute instance to become active
  go.mod
  go.sum
  openstack/resource_openstack_compute_instance_v2.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/common/extensions/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/delegate.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/shelveunshelve/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/shelveunshelve/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/shelveunshelve/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/startstop/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/urls.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#944 Add resource openstack_orchestration_stack_v1
  go.mod
  go.sum
  openstack/containerinfra_shared_v1.go
  openstack/import_openstack_orchestration_stack_v1_test.go
  openstack/orchestration_stack_v1.go
  openstack/provider.go
  openstack/resource_openstack_orchestration_stack_v1.go
  openstack/resource_openstack_orchestration_stack_v1_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/environment.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/fixtures.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/template.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/orchestration/v1/stacks/utils.go
  vendor/github.com/gophercloud/utils/terraform/auth/config.go
  website/docs/r/orchestration_stack_v1.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#947 Data source for openstack_blockstorage_volume_v3
  openstack/data_source_openstack_blockstorage_volume_v3.go
  openstack/data_source_openstack_blockstorage_volume_v3_test.go
  openstack/provider.go
  website/docs/d/blockstorage_volume_v3.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#945 Add max_retries_down to lb_monitor_v2 resource
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_monitor_v2_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/lb_monitor_v2.html.markdown
Labels: dependencies, documentation, size/XXL
