Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-05, with the labels that each got.

#747 Internal: Networking V2 Secgroup Rule cleanup
  openstack/networking_secgroup_rule_v2.go
  openstack/networking_secgroup_rule_v2_test.go
  openstack/resource_openstack_networking_secgroup_rule_v2.go
Labels: size/XL

#748 Networking v2: Make port dns_name computed
  openstack/resource_openstack_networking_port_v2.go
Labels: size/XS

#749 Acc Tests: Fix allocation_pool
  openstack/resource_openstack_networking_subnet_v2_test.go
Labels: size/XS

#750 Make timeout for stop_before_destroy configurable
  openstack/resource_openstack_compute_instance_v2.go
Labels: documentation, size/XS

#751 Acc Tests: Fix port binding syntax for v0.12
  openstack/resource_openstack_networking_port_v2_test.go
Labels: size/S

#752 DNS v2: Fix issue where TTL was being cleared
  go.mod
  go.sum
  openstack/resource_openstack_dns_recordset_v2.go
  openstack/resource_openstack_dns_recordset_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/dns/v2/recordsets/requests.go
  vendor/modules.txt
Labels: dependencies, size/M

#755 Fix Debug Memory Issue
  openstack/types.go
Labels: size/XS

#757 Mask identity v2 auth credentials
  openstack/types.go
Labels: size/XS
