Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-02, with the labels that each got.

#654 Manila: recreate share and its access resources, when the region is changed
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/resource_openstack_sharedfilesystem_share_v2.go
  website/docs/r/compute_instance_v2.html.markdown
  website/docs/r/sharedfilesystem_share_access_v2.html.markdown
  website/docs/r/sharedfilesystem_share_v2.html.markdown
Labels: documentation, size/XS

#560 Provider: Terraform v0.12 TypeMap Fixes
  openstack/data_source_openstack_containerinfra_clustertemplate_v1_test.go
  openstack/data_source_openstack_images_image_v2_test.go
  openstack/resource_openstack_blockstorage_volume_v1_test.go
  openstack/resource_openstack_blockstorage_volume_v2_test.go
  openstack/resource_openstack_blockstorage_volume_v3_test.go
  openstack/resource_openstack_compute_flavor_v2_test.go
  openstack/resource_openstack_containerinfra_cluster_v1_test.go
  openstack/resource_openstack_containerinfra_clustertemplate_v1_test.go
  openstack/resource_openstack_images_image_v2_test.go
  openstack/resource_openstack_lb_vip_v1_test.go
  openstack/resource_openstack_objectstorage_container_v1_test.go
  website/docs/d/images_image_v2.html.markdown
  website/docs/r/compute_flavor_v2.html.markdown
  website/docs/r/compute_instance_v2.html.markdown
  website/docs/r/containerinfra_clustertemplate_v1.html.markdown
  website/docs/r/images_image_v2.html.markdown
  website/docs/r/objectstorage_container_v1.html.markdown
Labels: documentation, size/M

#649 Network V2: Fix port data source all_fixed_ips attribute
  openstack/data_source_openstack_networking_port_ids_v2.go
  openstack/data_source_openstack_networking_port_v2.go
  openstack/data_source_openstack_networking_port_v2_test.go
  openstack/networking_port_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
Labels: size/M

#623 Networking V2: Don't conflict with the tags, being set ad-hoc
  openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2_test.go
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_port_secgroup_associate_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_router_v2.go
  openstack/resource_openstack_networking_secgroup_v2.go
  openstack/resource_openstack_networking_subnet_v2.go
  openstack/resource_openstack_networking_subnetpool_v2.go
  openstack/resource_openstack_networking_trunk_v2.go
  openstack/util.go
  website/docs/r/networking_floatingip_v2.html.markdown
  website/docs/r/networking_network_v2.html.markdown
  website/docs/r/networking_port_v2.html.markdown
  website/docs/r/networking_router_v2.html.markdown
  website/docs/r/networking_secgroup_v2.html.markdown
  website/docs/r/networking_subnet_v2.html.markdown
  website/docs/r/networking_subnetpool_v2.html.markdown
  website/docs/r/networking_trunk_v2.html.markdown
Labels: documentation, size/M

#641 Block Storage v2: Fix volume detachment 404s
  openstack/resource_openstack_blockstorage_volume_v1.go
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
Labels: size/S

#540 Compute v2: Retry multiattach volume attachments
  openstack/resource_openstack_compute_volume_attach_v2.go
Labels: size/XS

#661 Networking v2: Fix Allowed Address Pairs validation
  openstack/resource_openstack_networking_port_v2.go
Labels: size/XS

#669 Docs: Add section on Instances and Networks
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#670 Internal: openstack_compute_floatingip_associate_v2 cleanup
  openstack/compute_floatingip_associate_v2.go
  openstack/resource_openstack_compute_floatingip_associate_v2.go
Labels: size/L

#667 Internal: fwaas resources cleanup
  openstack/data_source_openstack_fw_policy_v1.go
  openstack/fw_firewall_v1.go
  openstack/fw_policy_v1.go
  openstack/fw_rule_v1.go
  openstack/fw_rule_v1_test.go
  openstack/resource_openstack_fw_firewall_v1.go
  openstack/resource_openstack_fw_policy_v1.go
  openstack/resource_openstack_fw_policy_v1_test.go
  openstack/resource_openstack_fw_rule_v1.go
  openstack/types.go
Labels: size/XL

#668 Networking v2: Deprecate openstack_networking_subnet_v2.host_routes
  openstack/resource_openstack_networking_subnet_v2.go
  website/docs/r/networking_subnet_v2.html.markdown
Labels: documentation, size/XS

#655 Add new data source 'openstack_compute_availability_zones_v2'
  openstack/data_source_openstack_compute_availability_zones_v2.go
  openstack/data_source_openstack_compute_availability_zones_v2_test.go
  openstack/provider.go
  website/docs/d/compute_availability_zones_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/M

#678 Networking v2: Revert validation of fixed_ip ip_address
  openstack/resource_openstack_networking_port_v2.go
Labels: size/XS

#660 Identity V3: Add application credential resource
  go.mod
  go.sum
  openstack/data_source_openstack_identity_auth_scope_v3.go
  openstack/identity_application_credential_v3.go
  openstack/identity_application_credential_v3_test.go
  openstack/import_openstack_identity_application_credential_v3_test.go
  openstack/provider.go
  openstack/resource_openstack_identity_application_credential_v3.go
  openstack/resource_openstack_identity_application_credential_v3_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/applicationcredentials/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/applicationcredentials/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/applicationcredentials/urls.go
  vendor/modules.txt
  website/docs/r/identity_application_credential_v3.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#652 Add ability to list availability zones for blockstorage and sharedfilesystem
  openstack/data_source_openstack_blockstorage_availability_zones_v3.go
  openstack/data_source_openstack_blockstorage_availability_zones_v3_test.go
  openstack/data_source_openstack_sharedfilesystem_availability_zones_v2.go
  openstack/data_source_openstack_sharedfilesystem_availability_zones_v2_test.go
  openstack/provider.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/availabilityzones/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/availabilityzones/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/availabilityzones/urls.go
  vendor/modules.txt
  website/docs/d/blockstorage_availability_zones_v3.html.markdown
  website/docs/d/sharedfilesystem_availability_zones_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#692 Acc Tests: Fixes for v0.12
  openstack/resource_openstack_networking_network_v2_test.go
  openstack/resource_openstack_networking_port_v2_test.go
  openstack/resource_openstack_objectstorage_object_v1_test.go
Labels: size/XS

#691 LBaaS V2: Detect null LB statuses result
  openstack/lb_v2_shared.go
Labels: size/XS

#689 Networking V2: Update port DHCP options in one API call
  openstack/networking_port_v2.go
  openstack/networking_port_v2_test.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
Labels: size/L
