Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-11, with the labels that each got.

#921 Auth: AllowReauth option should be exported
  openstack/config.go
  openstack/provider.go
Labels: size/XS

#628 Networking V2: Omit empty ExternalFixedIP IPAddress for the router
  openstack/resource_openstack_networking_router_v2.go
  openstack/resource_openstack_networking_router_v2_test.go
  website/docs/r/networking_router_v2.html.markdown
Labels: dependencies, documentation, size/M

#923 Missing character
  website/docs/r/identity_user_v3.html.markdown
Labels: documentation, size/XS

#933 Magnum - add fixed_network/fixed_subnet support
  openstack/data_source_openstack_containerinfra_cluster_v1.go
  openstack/resource_openstack_containerinfra_cluster_v1.go
Labels: size/XS

#934 Docs: update COE V1 cluster fixed net and subnet
  website/docs/d/containerinfra_cluster_v1.html.markdown
  website/docs/r/containerinfra_cluster_v1.html.markdown
Labels: documentation, size/XS
