Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-04, with the labels that each got.

#715 SharedFilesystem v2: Add cephx and access_key
  go.mod
  go.sum
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/util.go
  openstack/util_test.go
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/apiversions/urls.go
  vendor/modules.txt
  website/docs/r/sharedfilesystem_share_access_v2.html.markdown
Labels: dependencies, documentation, size/XL

#730 Correction for the master flavor
  openstack/resource_openstack_containerinfra_cluster_v1.go
Labels: size/XS

#671 Internal: Cleanup database resources
  openstack/db_configuration_v1.go
  openstack/db_configuration_v1_test.go
  openstack/db_database_v1.go
  openstack/db_instance_v1.go
  openstack/db_instance_v1_test.go
  openstack/db_user_v1.go
  openstack/db_user_v1_test.go
  openstack/resource_openstack_db_configuration_v1.go
  openstack/resource_openstack_db_database_v1.go
  openstack/resource_openstack_db_instance_v1.go
  openstack/resource_openstack_db_user_v1.go
Labels: size/XL

#737 Remove fixed_ip_v6 from the network block
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#738 SharedFilesystem v2: Fix access validation rules
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
Labels: size/XS

#740 Support acceptance test against OpenStack Stein release in OpenLab
  .zuul.yaml
Labels: size/XS

#739 Networking v2: Deprecate subnet allocation_pools for allocation_pool
  openstack/networking_subnet_v2.go
  openstack/networking_subnet_v2_test.go
  openstack/resource_openstack_networking_subnet_v2.go
  openstack/resource_openstack_networking_subnet_v2_test.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/compose.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/computed.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/condition.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/doc.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/force_new.go
  vendor/github.com/hashicorp/terraform/helper/customdiff/validate.go
  vendor/modules.txt
  website/docs/r/networking_subnet_v2.html.markdown
Labels: dependencies, documentation, size/XL

#745 vendor: update gophercloud/*
  go.mod
  go.sum
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_subnet_v2.go
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/containers/requests.go
  vendor/github.com/mitchellh/go-homedir/go.mod
  vendor/github.com/mitchellh/go-homedir/homedir.go
  vendor/modules.txt
Labels: dependencies, size/L

#741 Networking V2: add AddressScope datasource
  openstack/data_source_openstack_networking_addressscope_v2.go
  openstack/data_source_openstack_networking_addressscope_v2_test.go
  openstack/provider.go
  website/docs/d/networking_addressscope_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#680 Internal: Networking V2 Router Route cleanup
  openstack/networking_router_route_v2.go
  openstack/networking_router_route_v2_test.go
  openstack/resource_openstack_networking_router_route_v2.go
  openstack/resource_openstack_networking_router_route_v2_test.go
Labels: size/L

#746 Acc Tests: Add test for clearing a subnet's dns_nameservers
  openstack/resource_openstack_networking_subnet_v2_test.go
Labels: size/M
