Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-10, with the labels that each got.

#891 LBaaSv2: Properly handle update TLS references
  go.mod
  go.sum
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_listener_v2.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/volumes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/utils/openstack/clientconfig/doc.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#885 Compute V2: Handle empty scheduler_hints lists
  openstack/resource_openstack_compute_instance_v2.go
Labels: size/XS

#883 Lbaas v2: Properly handle 404 error on status checks
  openstack/lb_v2_shared.go
Labels: size/XS

#901 Shared filesystem V2: cleanup securityservice
  openstack/resource_openstack_sharedfilesystem_securityservice_v2.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2_test.go
  openstack/sharedfilesystem_shared_v2.go
Labels: size/M

#896 LBaaSv2: Add UDP protocol support
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_listener_v2_test.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_monitor_v2_test.go
  openstack/resource_openstack_lb_pool_v2.go
  openstack/resource_openstack_lb_pool_v2_test.go
  website/docs/r/lb_listener_v2.html.markdown
  website/docs/r/lb_monitor_v2.html.markdown
  website/docs/r/lb_pool_v2.html.markdown
Labels: documentation, size/L

#902 Shared filesystem V2: cleanup share access
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/sharedfilesystem_share_access_v2.go
  openstack/sharedfilesystem_shared_v2.go
Labels: size/M

#904 Fixed openstack_lb_loadbalancer_v2 flavor selection.
  go.mod
  go.sum
  openstack/resource_openstack_lb_loadbalancer_v2.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
  vendor/modules.txt
  website/docs/r/lb_loadbalancer_v2.html.markdown
Labels: dependencies, documentation, size/M

#907 Networking V2: add Quotas resource
  go.mod
  go.sum
  openstack/import_openstack_networking_quotas_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_networking_quotas_v2.go
  openstack/resource_openstack_networking_quotas_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/quotas/urls.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
  website/docs/r/networking_quotas_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#908 Update lb_pool_v2.html.markdown
  website/docs/r/lb_pool_v2.html.markdown
Labels: documentation, size/XS

#913 Auth: reuse existing token, when scope parameters are not defined
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/modules.txt
Labels: dependencies, size/M

#914 Compute V2: add Quotaset resource
  go.sum
  openstack/import_openstack_compute_quotasets_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_compute_quotaset_v2.go
  openstack/resource_openstack_compute_quotaset_v2_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/quotasets/urls.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/compute_quotaset_v2.html.markdown
  website/openstack.erb
Labels: dependencies, size/XXL

#915 Networking V2: rename "Quotas" resource to "Quota"
  openstack/import_openstack_networking_quotas_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_networking_quota_v2.go
  openstack/resource_openstack_networking_quota_v2_test.go
  website/docs/r/networking_quota_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#918 Auth: add "allow_reauth" configuration option
  openstack/config.go
  openstack/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS
