Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-01, with the labels that each got.

#526 Manila: add share acl resource
  openstack/import_openstack_sharedfilesystem_share_access_v2_test.go
  openstack/import_openstack_sharedfilesystem_share_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2_test.go
  openstack/resource_openstack_sharedfilesystem_share_v2.go
  openstack/resource_openstack_sharedfilesystem_share_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/errors/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/urls.go
  vendor/vendor.json
  website/docs/r/sharedfilesystem_share_access_v2.html.markdown
  website/docs/r/sharedfilesystem_share_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#413 When calling API endpoints, allow a certain amount of retries
  openstack/config.go
  openstack/provider.go
  openstack/types.go
Labels: size/S

#544 Internal: Block Storage volumes cleanup
  openstack/blockstorage_volume_v1.go
  openstack/blockstorage_volume_v1_test.go
  openstack/blockstorage_volume_v2.go
  openstack/blockstorage_volume_v2_test.go
  openstack/blockstorage_volume_v3.go
  openstack/blockstorage_volume_v3_test.go
  openstack/resource_openstack_blockstorage_volume_attach_v2.go
  openstack/resource_openstack_blockstorage_volume_attach_v3.go
  openstack/resource_openstack_blockstorage_volume_v1.go
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
  openstack/util.go
  openstack/util_test.go
Labels: size/XL

#556 LBaaSv2: Prioritize loadbalancer's status in favour of subelements
  openstack/lb_v2_shared.go
Labels: documentation, size/L

#566 Provider: spelling and comment details
  openstack/types.go
Labels: size/XS

#538 NetworkingV2: add transparent_vlan network datasource attribute
  openstack/data_source_openstack_networking_network_v2.go
  openstack/data_source_openstack_networking_network_v2_test.go
  vendor/vendor.json
  website/docs/d/networking_network_v2.html.markdown
Labels: dependencies, documentation, size/M

#567 Networking: add port data source
  openstack/data_source_openstack_networking_port_v2.go
  openstack/data_source_openstack_networking_port_v2_test.go
  openstack/lb_v2_shared.go
  openstack/provider.go
  openstack/util.go
  website/docs/d/networking_port_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#572 Internal: Floating IP associate cleanup
  openstack/networking_floatingip_v2.go
  openstack/resource_openstack_networking_floatingip_associate_v2.go
  openstack/resource_openstack_networking_floatingip_associate_v2_test.go
Labels: size/M

#576 Manila: add share network data source
  openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2.go
  openstack/data_source_openstack_sharedfilesystem_sharenetwork_v2_test.go
  openstack/import_openstack_sharedfilesystem_sharenetwork_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_sharedfilesystem_sharenetwork_v2.go
  openstack/resource_openstack_sharedfilesystem_sharenetwork_v2_test.go
  website/docs/d/sharedfilesystem_sharenetwork_v2.html.markdown
  website/docs/r/sharedfilesystem_sharenetwork_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#583 Manila: fix pending state for deleted share
  openstack/resource_openstack_sharedfilesystem_share_v2.go
Labels: size/XS

#590 Object storage: fix etag tests race condition
  openstack/resource_openstack_objectstorage_object_v1_test.go
Labels: size/XS

#594 Networking v2: Fix Port admin_state_up behavior
  openstack/resource_openstack_networking_port_v2.go
  openstack/resource_openstack_networking_port_v2_test.go
Labels: size/L

#592 Internal: Add ID to CheckDeleted
  openstack/resource_openstack_compute_flavor_v2.go
  openstack/resource_openstack_compute_floatingip_v2.go
  openstack/resource_openstack_compute_keypair_v2.go
  openstack/resource_openstack_compute_secgroup_v2.go
  openstack/resource_openstack_compute_servergroup_v2.go
  openstack/resource_openstack_dns_recordset_v2.go
  openstack/resource_openstack_dns_zone_v2.go
  openstack/util.go
Labels: size/XS

#585 Internal: block storage snapshots cleanup
  openstack/blockstorage_snapshot_v2.go
  openstack/blockstorage_snapshot_v3.go
  openstack/data_source_openstack_blockstorage_snapshot_v2.go
  openstack/data_source_openstack_blockstorage_snapshot_v3.go
  openstack/types.go
Labels: size/M

#571 Internal: Floating IP cleanup
  openstack/data_source_openstack_networking_floatingip_v2.go
  openstack/data_source_openstack_networking_floatingip_v2_test.go
  openstack/networking_floatingip_v2.go
  openstack/networking_network_v2.go
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_floatingip_v2_test.go
Labels: size/XL

#577 Manila: add share snapshot data source
  openstack/data_source_openstack_sharedfilesystem_snapshot_v2.go
  openstack/data_source_openstack_sharedfilesystem_snapshot_v2_test.go
  openstack/provider.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/subnets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/snapshots/urls.go
  vendor/vendor.json
  website/docs/d/sharedfilesystem_snapshot_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#596 Manila: introduce manila messages for detailed share errors
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/resource_openstack_sharedfilesystem_share_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/messages/urls.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/vendor.json
Labels: dependencies, size/XL

#539 Compute v2: Fix Instance NIC indexing
  openstack/compute_instance_v2_networking.go
Labels: size/XS

#600 Manila: add CheckDeleted into the Delete functions
  openstack/resource_openstack_sharedfilesystem_securityservice_v2.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
  openstack/resource_openstack_sharedfilesystem_share_v2.go
  openstack/resource_openstack_sharedfilesystem_sharenetwork_v2.go
Labels: size/XS

#587 Compute v2: add flavor_id to flavor data source
  openstack/data_source_openstack_compute_flavor_v2.go
  openstack/data_source_openstack_compute_flavor_v2_test.go
  website/docs/d/compute_flavor_v2.html.markdown
Labels: documentation, size/M

#603 Manila: fix doc captions
  website/openstack.erb
Labels: documentation, size/XS

#599 LBaaSv2: add CheckDeleted into the Delete functions
  openstack/resource_openstack_lb_l7policy_v2.go
  openstack/resource_openstack_lb_l7rule_v2.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_monitor_v2.go
  openstack/resource_openstack_lb_pool_v2.go
Labels: size/S

#607 Fix links and go version requirement
  README.md
  website/docs/d/images_image_v2.html.markdown
  website/docs/index.html.markdown
  website/docs/r/compute_instance_v2.html.markdown
  website/docs/r/images_image_v2.html.markdown
Labels: documentation, size/XS

#595 Internal: Networking V2 Router interface cleanup
  openstack/networking_router_interface_v2.go
  openstack/resource_openstack_networking_router_interface_v2.go
Labels: size/L

#584 Internal: cleanup Networking V2 Ports
  openstack/data_source_openstack_networking_port_ids_v2.go
  openstack/data_source_openstack_networking_port_v2.go
  openstack/networking_port_v2.go
  openstack/networking_port_v2_test.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_networking_port_v2.go
Labels: size/XL

#615 Internal: fix schema set for the image data source
  openstack/data_source_openstack_images_image_v2.go
  website/docs/d/images_image_v2.html.markdown
Labels: documentation, size/XS

#619 Internal: fix schema set for the subnetpool resource
  openstack/resource_openstack_networking_subnetpool_v2.go
Labels: size/XS

#616 Internal: fix schema set for the subnetpool data source
  openstack/data_source_openstack_networking_subnetpool_v2.go
Labels: size/XS

#606 Networking V2: fix fip disassociating on description update
  openstack/resource_openstack_compute_floatingip_associate_v2_test.go
  openstack/resource_openstack_networking_floatingip_associate_v2.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/vendor.json
Labels: dependencies, size/XL

#611 Internal: identity group cleanup
  openstack/data_source_openstack_identity_group_v3.go
Labels: size/XS

#610 Internal: identity endpoint cleanup
  openstack/data_source_openstack_identity_endpoint_v3.go
Labels: size/S

#593 Networking v2: Fix boolean fields of network resource
  openstack/resource_openstack_networking_network_v2.go
  openstack/resource_openstack_networking_network_v2_test.go
Labels: size/L

#631 Networking V2: Fix port data sources
  openstack/data_source_openstack_networking_port_ids_v2.go
  openstack/data_source_openstack_networking_port_v2.go
  openstack/data_source_openstack_networking_port_v2_test.go
  website/docs/d/networking_port_ids_v2.html.markdown
  website/docs/d/networking_port_v2.html.markdown
Labels: documentation, size/M

#625 Networking V2: add description to the trunk resource
  openstack/resource_openstack_networking_trunk_v2.go
  openstack/resource_openstack_networking_trunk_v2_test.go
  website/docs/r/networking_trunk_v2.html.markdown
Labels: documentation, size/S

#624 Networking V2: Add tags into the data sources
  openstack/data_source_openstack_fw_policy_v1.go
  openstack/data_source_openstack_networking_floatingip_v2.go
  openstack/data_source_openstack_networking_floatingip_v2_test.go
  openstack/data_source_openstack_networking_network_v2.go
  openstack/data_source_openstack_networking_network_v2_test.go
  openstack/data_source_openstack_networking_port_ids_v2.go
  openstack/data_source_openstack_networking_port_v2.go
  openstack/data_source_openstack_networking_router_v2.go
  openstack/data_source_openstack_networking_router_v2_test.go
  openstack/data_source_openstack_networking_secgroup_v2.go
  openstack/data_source_openstack_networking_secgroup_v2_test.go
  openstack/data_source_openstack_networking_subnet_v2.go
  openstack/data_source_openstack_networking_subnet_v2_test.go
  openstack/data_source_openstack_networking_subnetpool_v2.go
  openstack/data_source_openstack_networking_subnetpool_v2_test.go
  website/docs/d/networking_floatingip_v2.html.markdown
  website/docs/d/networking_network_v2.html.markdown
  website/docs/d/networking_router_v2.html.markdown
  website/docs/d/networking_secgroup_v2.html.markdown
  website/docs/d/networking_subnet_v2.html.markdown
  website/docs/d/networking_subnetpool_v2.html.markdown
Labels: documentation, size/XL

#609 Internal: identity auth scope cleanup
  openstack/data_source_openstack_identity_auth_scope_v3.go
  openstack/identity_auth_scope_v3.go
  openstack/identity_auth_scope_v3_test.go
Labels: size/M

#613 Internal: identity roles cleanup
  openstack/data_source_openstack_identity_role_v3.go
  openstack/identity_role_assignment_v3.go
  openstack/identity_role_assignment_v3_test.go
  openstack/resource_openstack_identity_role_assignment_v3.go
  openstack/resource_openstack_identity_role_assignment_v3_test.go
  openstack/resource_openstack_identity_role_v3.go
Labels: size/L

#635 Vet: fix unkeyed fields for importers
  openstack/resource_openstack_lb_l7policy_v2.go
  openstack/resource_openstack_lb_l7rule_v2.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_pool_v2.go
  openstack/resource_openstack_sharedfilesystem_share_access_v2.go
Labels: size/XS

#632 Internal: Networking V2 Trunk resource cleanup
  openstack/networking_trunk_v2.go
  openstack/networking_trunk_v2_test.go
  openstack/resource_openstack_networking_trunk_v2.go
  website/docs/r/networking_trunk_v2.html.markdown
Labels: documentation, size/XL

#633 Internal: Networking V2 Subnetpool cleanup
  openstack/data_source_openstack_networking_subnetpool_v2.go
  openstack/networking_subnetpool_v2.go
  openstack/resource_openstack_networking_subnetpool_v2.go
Labels: size/L

#636 DNS v2: Fix recordset diffs
  openstack/dns_recordset_v2.go
  openstack/dns_recordset_v2_test.go
  openstack/resource_openstack_dns_recordset_v2.go
  website/docs/r/dns_recordset_v2.html.markdown
Labels: documentation, size/M

#634 Networking V2: add Address-scope resource
  openstack/import_openstack_networking_addressscope_v2_test.go
  openstack/networking_addressscope_v2.go
  openstack/provider.go
  openstack/resource_openstack_networking_addressscope_v2.go
  openstack/resource_openstack_networking_addressscope_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/addressscopes/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/vendor.json
  website/docs/r/networking_addressscope_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#614 Internal: identity user cleanup
  openstack/data_source_openstack_identity_user_v3.go
  openstack/identity_user_v3.go
  openstack/identity_user_v3_test.go
  openstack/resource_openstack_identity_user_v3.go
Labels: size/L

#574 Networking: add port secgroup associate resource
  openstack/provider.go
  openstack/resource_openstack_networking_port_secgroup_associate_v2.go
  openstack/resource_openstack_networking_port_secgroup_associate_v2_test.go
  openstack/util.go
  website/docs/r/networking_port_secgroup_associate_v2.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#644 Networking v2: Fix 409 bug with network refresh
  openstack/networking_network_v2.go
Labels: size/XS

#647 Compute V2: Don't fail on delete, when compute instance doesn't exist
  openstack/identity_user_v3_test.go
  openstack/import_openstack_compute_interface_attach_v2_test.go
  openstack/resource_openstack_compute_instance_v2.go
Labels: size/XS
