Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2019-08, with the labels that each got.

#808 Keymanager V1: container resource
  go.mod
  go.sum
  openstack/import_openstack_keymanager_container_v1_test.go
  openstack/keymanager_container_v1.go
  openstack/provider.go
  openstack/resource_openstack_keymanager_container_v1.go
  openstack/resource_openstack_keymanager_container_v1_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/containers/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/modules.txt
  website/docs/r/keymanager_container_v1.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XXL

#821 Identity V3: Add identity service resource
  openstack/import_openstack_identity_service_v3_test.go
  openstack/provider.go
  openstack/resource_openstack_identity_service_v3.go
  openstack/resource_openstack_identity_service_v3_test.go
  website/docs/r/identity_service_v3.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#825 Manila V2: Allow modification of the share metadata
  go.mod
  go.sum
  openstack/resource_openstack_sharedfilesystem_share_v2.go
  openstack/resource_openstack_sharedfilesystem_share_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/sharedfilesystems/v2/shares/urls.go
  vendor/modules.txt
  website/docs/r/sharedfilesystem_share_v2.html.markdown
Labels: dependencies, documentation, size/XL

#725 LBaaS V2: Add flatten func for the lb pool
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_pool_v2.go
Labels: size/XS

#815 Key manager v1: add secret data source
  openstack/data_source_openstack_keymanager_secret_v1.go
  openstack/data_source_openstack_keymanager_secret_v1_test.go
  openstack/provider.go
  website/docs/d/keymanager_secret_v1.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#811 Networking v2: Add neutron rbac policy resource
  openstack/import_openstack_networking_rbac_policy_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_networking_rbac_policy_v2.go
  openstack/resource_openstack_networking_rbac_policy_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/rbacpolicies/urls.go
  vendor/modules.txt
  website/docs/r/networking_rbac_policy_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#817 Identity V3: Fix endpoint data source filtering
  go.mod
  go.sum
  openstack/data_source_openstack_identity_endpoint_v3.go
  openstack/data_source_openstack_identity_endpoint_v3_test.go
  openstack/identity_endpoint_v3.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/endpoints/requests.go
  vendor/modules.txt
  website/docs/d/identity_endpoint_v3.html.markdown
Labels: dependencies, documentation, size/L

#819 Identity V3: Add service data source
  openstack/data_source_openstack_identity_service_v3.go
  openstack/data_source_openstack_identity_service_v3_test.go
  openstack/provider.go
  website/docs/d/identity_service_v3.html.markdown
  website/openstack.erb
Labels: documentation, size/L

#806 BlockStorage V2: add Quotaset resource
  go.mod
  go.sum
  openstack/import_openstack_blockstorage_quotaset_v2_test.go
  openstack/provider.go
  openstack/resource_openstack_blockstorage_quotaset_v2.go
  openstack/resource_openstack_blockstorage_quotaset_v2_test.go
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/quotasets/urls.go
  vendor/modules.txt
  website/docs/r/blockstorage_quotaset_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#823 Identity V3: Add identity endpoint resource
  openstack/import_openstack_identity_endpoint_v3_test.go
  openstack/provider.go
  openstack/resource_openstack_identity_endpoint_v3.go
  openstack/resource_openstack_identity_endpoint_v3_test.go
  website/docs/r/identity_endpoint_v3.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#826 Fix typo in security_groups argument
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#759 Proper handling of the empty "binding:profile"
  openstack/networking_port_v2.go
  openstack/resource_openstack_networking_port_v2.go
  openstack/util.go
Labels: dependencies, size/M

#828 Blockstorage V3: add quotaset resource
  openstack/import_openstack_blockstorage_quotaset_v3_test.go
  openstack/provider.go
  openstack/resource_openstack_blockstorage_quotaset_v3.go
  openstack/resource_openstack_blockstorage_quotaset_v3_test.go
  website/docs/r/blockstorage_quotaset_v3.html.markdown
  website/openstack.erb
Labels: documentation, size/XL

#831 Vendor: update Gophercloud for time format fix
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/subnetpools/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/modules.txt
Labels: dependencies, size/L

#834 Update compute_instance_v2.html.markdown
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#839 LBaaS V2: Don't fallback to 'DELETE' status, when statuses are not available
  openstack/lb_v2_shared.go
Labels: size/XS

#837 Networking V2: Mark dns attributes as computed
  openstack/resource_openstack_networking_floatingip_v2.go
  openstack/resource_openstack_networking_network_v2.go
Labels: size/XS

#840 LBaaS V2: Add OpenContrail monitor workaround
  openstack/resource_openstack_lb_monitor_v2.go
  website/docs/r/lb_monitor_v2.html.markdown
Labels: documentation, size/XS
