Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2020-05, with the labels that each got.

#985 Compute v2: Introduce an availability_zone_hints parameter
  openstack/resource_openstack_compute_instance_v2.go
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS

#993 Add SOURCE_IP_PORT load balancing method
  openstack/resource_openstack_lb_pool_v2.go
  website/docs/r/lb_pool_v2.html.markdown
Labels: documentation, size/XS

#997 Keymanager V1: Print error log in keyManagerSecretV1GetPayload func
  openstack/keymanager_secret_v1.go
Labels: size/XS

#996 Enable delayed_auth and allow_reauth options by default
  openstack/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/S

#978 Add Project Tags
  openstack/data_source_openstack_identity_project_v3.go
  openstack/data_source_openstack_identity_project_v3_test.go
  openstack/data_source_openstack_identity_user_v3_test.go
  openstack/resource_openstack_identity_project_v3.go
  openstack/resource_openstack_identity_project_v3_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/d/identity_project_v3.html.markdown
  website/docs/r/identity_project_v3.html.markdown
Labels: dependencies, size/XXL

#1000 Networking V2: cleanup secgroup resource
  openstack/networking_secgroup_v2.go
  openstack/resource_openstack_networking_secgroup_v2.go
  openstack/resource_openstack_networking_secgroup_v2_test.go
Labels: size/L

#900 Networking: cleanup subnet V2
  openstack/data_source_openstack_networking_subnet_v2.go
  openstack/networking_subnet_v2.go
  openstack/networking_subnet_v2_test.go
  openstack/resource_openstack_networking_subnet_v2.go
  openstack/util.go
Labels: size/XL

#999 Networking V2: cleanup subnet route resource
  openstack/networking_subnet_route_v2.go
  openstack/networking_subnet_route_v2_test.go
  openstack/resource_openstack_networking_subnet_route_v2.go
  openstack/resource_openstack_networking_subnet_route_v2_test.go
Labels: size/L

#983 Add blockstorage scheduler hints
  openstack/blockstorage_extensions.go
  openstack/blockstorage_extensions_test.go
  openstack/resource_openstack_blockstorage_volume_v2.go
  openstack/resource_openstack_blockstorage_volume_v3.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerhints/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/schedulerhints/requests.go
  vendor/modules.txt
  website/docs/r/blockstorage_volume_v2.html.markdown
  website/docs/r/blockstorage_volume_v3.html.markdown
Labels: dependencies, documentation, size/XL

#937 Add containerinfra_cluster kubeconfig attribute
  go.mod
  openstack/containerinfra_shared_v1.go
  openstack/resource_openstack_containerinfra_cluster_v1.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates/urls.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/containerinfra_cluster_v1.html.markdown
Labels: dependencies, size/XXL

#1001 Set Go version to 1.14.2
  .go-version
  .travis.yml
  README.md
  go.mod
  vendor/modules.txt
Labels: dependencies, size/S

#1006 Fix go vet "composite literal uses unkeyed fields"
  openstack/lb_v2_shared.go
Labels: size/XS

#984 Add compute_instance_v2 data source
  openstack/data_source_openstack_compute_instance_v2.go
  openstack/data_source_openstack_compute_instance_v2_test.go
  openstack/provider.go
  website/docs/d/compute_instance_v2.html.markdown
Labels: documentation, size/XL

#948 Add vip_network_id for octavia
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_loadbalancer_v2.go
  openstack/resource_openstack_lb_loadbalancer_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/loadbalancers/urls.go
  vendor/modules.txt
  website/docs/r/lb_loadbalancer_v2.html.markdown
Labels: dependencies, documentation, size/XXL

#1009 Docs: cleanup Networking Port V2 docs
  website/docs/r/networking_port_v2.html.markdown
Labels: documentation, size/XS

#1017 Compute V2: Allow to filter flavors by visibility in data source
  openstack/data_source_openstack_compute_flavor_v2.go
  website/docs/d/compute_flavor_v2.html.markdown
Labels: documentation, size/XS
