Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2020-08, with the labels that each got.

#1034 Add "allowed_cidrs" option for Octavia listeners
  openstack/lb_v2_shared.go
  openstack/resource_openstack_lb_listener_v2.go
  website/docs/r/lb_listener_v2.html.markdown
Labels: documentation, size/S

#1033 Add identity_ec2_credential resource
  go.sum
  openstack/import_openstack_identity_ec2_credential_v3_test.go
  openstack/provider.go
  openstack/resource_openstack_identity_ec2_credential_v3.go
  openstack/resource_openstack_identity_ec2_credential_v3_test.go
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/ec2credentials/urls.go
  vendor/modules.txt
  website/docs/r/identity_ec2_credential_v3.html.markdown
Labels: dependencies, documentation, size/XL

#1039 Fix merge labels
  openstack/resource_openstack_containerinfra_cluster_v1.go
Labels: documentation, size/XS

#1044 Identity V3: reduce keystone requests amount
  openstack/data_source_openstack_identity_auth_scope_v3.go
  openstack/data_source_openstack_identity_project_v3.go
  openstack/identity_auth_scope_v3.go
  openstack/resource_openstack_identity_application_credential_v3.go
  openstack/resource_openstack_identity_ec2_credential_v3.go
Labels: size/L

#1031 Swift: run tempurl acceptance tests with slashes in object name
  go.mod
  go.sum
  openstack/resource_openstack_objectstorage_tempurl_v1_test.go
  vendor/github.com/gophercloud/gophercloud/.travis.yml
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/go.sum
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/servers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/objectstorage/v1/objects/requests.go
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
Labels: dependencies, size/L

#1046 Keymanager V1: fix ACL set for the "certificate" container type
  openstack/resource_openstack_keymanager_container_v1.go
  openstack/resource_openstack_keymanager_container_v1_test.go
Labels: size/M

#1043 feat: add floating_ip_enabled in containerinfra
  openstack/data_source_openstack_containerinfra_cluster_v1.go
Labels: size/XS

#1049 docs: update Rackspace compatibility notes
  website/docs/index.html.markdown
Labels: documentation, size/XS

#1051 Update Terraform SDK to v1.15.0, use Go 1.14.7
  .go-version
  README.md
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-checkpoint/LICENSE
  vendor/github.com/hashicorp/go-checkpoint/README.md
  vendor/github.com/hashicorp/go-checkpoint/check.go
  vendor/github.com/hashicorp/go-checkpoint/go.mod
  vendor/github.com/hashicorp/go-checkpoint/go.sum
  vendor/github.com/hashicorp/go-checkpoint/telemetry.go
  vendor/github.com/hashicorp/go-checkpoint/versions.go
  vendor/github.com/hashicorp/terraform-exec/LICENSE
  vendor/github.com/hashicorp/terraform-exec/tfinstall/pubkey.go
  vendor/github.com/hashicorp/terraform-exec/tfinstall/tfinstall.go
  vendor/github.com/hashicorp/terraform-exec/tfinstall/version.go
  vendor/github.com/hashicorp/terraform-json/schemas.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-test/CHANGELOG.md
  vendor/github.com/hashicorp/terraform-plugin-test/config.go
  vendor/github.com/hashicorp/terraform-plugin-test/go.mod
  vendor/github.com/hashicorp/terraform-plugin-test/go.sum
  vendor/github.com/hashicorp/terraform-plugin-test/helper.go
  vendor/github.com/hashicorp/terraform-plugin-test/terraform.go
  vendor/github.com/hashicorp/terraform-plugin-test/working_dir.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#1052 Keystone v3: fix ec2 credentials typo in docs
  website/docs/r/identity_ec2_credential_v3.html.markdown
Labels: documentation, size/XS

#1053 Add a link to ec2 cred doc
  website/openstack.erb
Labels: documentation, size/XS
