Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2020-06, with the labels that each got.

#1018 Bump gophercloud version
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/bootfromvolume/urls.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/certificates/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v2/tenants/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/extensions/oauth1/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/projects/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/images/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/qos/policies/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/trunks/doc.go
  vendor/github.com/gophercloud/gophercloud/results.go
  vendor/modules.txt
Labels: dependencies, size/L

#1020 Upgrage Gophercloud to v0.12.0
  go.mod
  go.sum
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/openstack/containerinfra/v1/clusters/requests.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
  vendor/modules.txt
Labels: dependencies, size/M

#1022 Set Go version to 1.14.4
  .go-version
Labels: size/XS
