Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2020-04, with the labels that each got.

#888 Image create using import web-download
  CHANGELOG.md
  openstack/provider_test.go
  openstack/resource_openstack_images_image_v2.go
  openstack/resource_openstack_images_image_v2_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/imageservice/v2/imageimport/urls.go
  vendor/modules.txt
  website/docs/r/images_image_v2.html.markdown
Labels: dependencies, documentation, size/L

#992 Add support for barbican order resources
  openstack/import_openstack_keymanager_order_v1_test.go
  openstack/keymanager_order_v1.go
  openstack/provider.go
  openstack/resource_openstack_keymanager_order_v1.go
  openstack/resource_openstack_keymanager_order_v1_test.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/orders/doc.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/orders/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/orders/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/keymanager/v1/orders/urls.go
  website/docs/r/keymanager_order_v1.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#986 Update object verisoning documentation URL
  website/docs/r/objectstorage_container_v1.html.markdown
Labels: documentation, size/XS

#987 Add ACL examples
  website/docs/r/objectstorage_container_v1.html.markdown
Labels: documentation, size/S

#898 LBaaS v2: Add batch members update resource
  openstack/import_openstack_lb_members_v2_test.go
  openstack/lb_v2_shared.go
  openstack/provider.go
  openstack/provider_test.go
  openstack/resource_openstack_lb_member_v2.go
  openstack/resource_openstack_lb_members_v2.go
  openstack/resource_openstack_lb_members_v2_test.go
  website/docs/r/lb_member_v2.html.markdown
  website/docs/r/lb_members_v2.html.markdown
  website/openstack.erb
Labels: dependencies, documentation, size/XL

#994 Implemented Security Group Rule Mutex
  openstack/resource_openstack_networking_secgroup_rule_v2.go
Labels: size/XS

#998 Object Storage Container V1: Add reading fields and import
  openstack/import_openstack_objectstorage_container_v1_test.go
  openstack/resource_openstack_objectstorage_container_v1.go
  openstack/resource_openstack_objectstorage_container_v1_test.go
  website/docs/r/objectstorage_container_v1.html.markdown
Labels: documentation, size/M
