Repository terraform-provider-openstack/terraform-provider-openstack, pull requests merged in 2020-02, with the labels that each got.

#964 Remove mitaka test job "terraform-provider-openstack-acceptance-test-mitaka" which use ubuntu-trusty
  .zuul.yaml
Labels: size/XS

#959 Add "insert_headers" argument for lb_listener_v2
  go.mod
  go.sum
  openstack/import_openstack_lb_listener_v2_test.go
  openstack/lb_v2_shared.go
  openstack/lb_v2_shared_test.go
  openstack/resource_openstack_lb_l7policy_v2_test.go
  openstack/resource_openstack_lb_l7rule_v2_test.go
  openstack/resource_openstack_lb_listener_v2.go
  openstack/resource_openstack_lb_listener_v2_test.go
  openstack/resource_openstack_lb_loadbalancer_v2_test.go
  openstack/resource_openstack_lb_member_v2_test.go
  openstack/resource_openstack_lb_monitor_v2_test.go
  openstack/resource_openstack_lb_pool_v2_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/gophercloud/gophercloud/.zuul.yaml
  vendor/github.com/gophercloud/gophercloud/CHANGELOG.md
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/go.mod
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas/vips/results.go
  vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/lb_listener_v2.html.markdown
Labels: dependencies, size/XXL

#967 Remove mitaka check job as ubuntu-trusty is EOL(fix-go-sum)
  .zuul.yaml
Labels: size/XS

#966 Remove mitaka check job as ubuntu-trusty is EOL(f-user-agent)
  .zuul.yaml
Labels: size/XS

#963 implement support for volume_type in block_device of openstack_compute_instance_v2
  openstack/compute_instance_v2.go
  openstack/resource_openstack_compute_instance_v2.go
  website/docs/r/compute_instance_v2.html.markdown
Labels: documentation, size/XS
